### ISSUE TITLE
[Feature Request] AnvilLogin Support

### ISSUE THREAD

**Issue by FunkyNico** [LagBug/XProtect#4]
Hello, i would like to see implemented AnvilLogin plugin support. What this plugin does it's allows you to login to your server using an 'AnvilGUI'. An AnvilGUI is basically a Anvil inventory, that receives strings inputted by the user.

AnvilLogin has AuthMe support already, and XProtect has it also. So i think it would be a nice combo to have XProtect+AnvilGUI+Authme. The main goal would be to no have any kind of issue to first register or login with AnvilLogin and then solve the respective captcha of XProtect.

[AnvilLogin Gitlab](https://gitlab.com/SamB440/AnvilLogin)
[AnvilLogin Gitlab Feature Request](https://gitlab.com/SamB440/AnvilLogin/-/issues/11)
[AnvilLogin Spigot Resource Page](https://www.spigotmc.org/resources/anvillogin.31861/)

Thanks.

**Comment by LagBug** [comment]
Hey, unfortunantly I can't seem to be able to find an API for AnvilLogin, so I currently can't do much.

**Comment by SamB440** [comment]
The idea was AnvilLogin would add support to XProtect itself via API, but at the time this issue was created, the source code/API was not present anywhere, so it's on me to add support for it now that it is possible.

Also I'd like to suggest you make the project multi-modular: this way api jars and the plugin jars can be built independently, and if you had never open sourced this project, an api jar could still have been shared. Even now it would be ideal because then the API can be published to a repository without the plugin itself being there.

**Comment by LagBug** [comment]
> The idea was AnvilLogin would add support to XProtect itself via API, but at the time this issue was created, the source code/API was not present anywhere, so it's on me to add support for it now that it is possible.
> 
> Also I'd like to suggest you make the project multi-modular: this way api jars and the plugin jars can be built independently, and if you had never open sourced this project, an api jar could still have been shared. Even now it would be ideal because then the API can be published to a repository without the plugin itself being there.

Perfect! As for the multi-modular idea, I think it's pretty good. Currently I don't have that much time to do it, but hopefullt in the future I'll get to do it.
